# Generated by Django 2.2.24 on 2021-10-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('Kode', models.AutoField(db_column='Kode', primary_key=True, serialize=False)),
                ('NamaAkun', models.CharField(blank=True, db_column='NamaAkun', max_length=250, null=True)),
                ('Saldo', models.IntegerField(db_column='Saldo')),
                ('Keterangan', models.TextField(blank=True, db_column='Keterangan', max_length=250, null=True)),
            ],
            options={
                'db_table': 'Akun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('Kode', models.AutoField(db_column='Kode', primary_key=True, serialize=False)),
                ('Tanggal', models.DateTimeField(blank=True, db_column='Tanggal', null=True)),
                ('Nominal', models.IntegerField(db_column='Nominal', default=0)),
                ('Keterangan', models.CharField(db_column='Keterangan', max_length=250)),
            ],
            options={
                'db_table': 'Bonus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('Kode', models.AutoField(db_column='Kode', primary_key=True, serialize=False)),
                ('Tanggal', models.DateTimeField(blank=True, db_column='Tanggal', null=True)),
                ('Nominal', models.IntegerField(db_column='Nominal', default=0)),
                ('Referensi', models.CharField(db_column='Referensi', max_length=50)),
                ('Charge', models.IntegerField(db_column='Charge', default=0)),
            ],
            options={
                'db_table': 'Deposit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('Kode', models.AutoField(db_column='Kode', primary_key=True, serialize=False)),
                ('Username', models.CharField(db_column='Username', max_length=50)),
                ('Nama', models.CharField(blank=True, db_column='Nama', max_length=250, null=True)),
                ('Phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('Email', models.CharField(blank=True, db_column='Email', max_length=250, null=True)),
                ('Bank', models.CharField(blank=True, db_column='Bank', max_length=50, null=True)),
                ('NoRekening', models.CharField(blank=True, db_column='NoRekening', max_length=50, null=True)),
                ('Saldo', models.IntegerField(db_column='Saldo')),
                ('Keterangan', models.TextField(db_column='Keterangan')),
            ],
            options={
                'db_table': 'Player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('Kode', models.AutoField(db_column='Kode', primary_key=True, serialize=False)),
                ('Nama', models.CharField(blank=True, db_column='Nama', max_length=250, null=True)),
                ('Keterangan', models.CharField(blank=True, db_column='Keterangan', max_length=250, null=True)),
            ],
            options={
                'db_table': 'Promo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telemarketing',
            fields=[
                ('Kode', models.AutoField(db_column='Kode', primary_key=True, serialize=False)),
                ('Nama', models.CharField(blank=True, db_column='Nama', max_length=250, null=True)),
            ],
            options={
                'db_table': 'Telemarketing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransferAntarAkun',
            fields=[
                ('Kode', models.AutoField(db_column='Kode', primary_key=True, serialize=False)),
                ('Tanggal', models.DateTimeField(blank=True, db_column='Tanggal', null=True)),
                ('Nominal', models.IntegerField(db_column='Nominal', default=0)),
                ('Charge', models.IntegerField(db_column='Charge', default=0)),
            ],
            options={
                'db_table': 'TransferAntarAkun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('Kode', models.AutoField(db_column='Kode', primary_key=True, serialize=False)),
                ('Tanggal', models.DateTimeField(blank=True, db_column='Tanggal', null=True)),
                ('Nominal', models.IntegerField(db_column='Nominal', default=0)),
                ('Referensi', models.CharField(db_column='Referensi', max_length=50)),
                ('Charge', models.IntegerField(db_column='Charge', default=0)),
            ],
            options={
                'db_table': 'Withdraw',
                'managed': False,
            },
        ),
    ]
